package Figuras;
public class VentanaPrincipal extends javax.swing.JFrame {
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtCRadio = new javax.swing.JTextField();
        txtCArea = new javax.swing.JTextField();
        txtCPerimetro = new javax.swing.JTextField();
        btnArea = new javax.swing.JButton();
        btnPerimetro = new javax.swing.JButton();
        btnCiBorrar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtCuLado = new javax.swing.JTextField();
        txtCuArea = new javax.swing.JTextField();
        txtCuPerimetro = new javax.swing.JTextField();
        btnCuCalcularArea = new javax.swing.JButton();
        btnCuCalcularPerimetro = new javax.swing.JButton();
        btnCuBorrar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtRBase = new javax.swing.JTextField();
        txtRAltura = new javax.swing.JTextField();
        txtRArea = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtRPerimetro = new javax.swing.JTextField();
        btnRCalcularArea = new javax.swing.JButton();
        btnRCalcularPerimetro = new javax.swing.JButton();
        btnRBorrar = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        txtTBase = new javax.swing.JTextField();
        txtTAltura = new javax.swing.JTextField();
        txtTHipotenusa = new javax.swing.JTextField();
        txtTArea = new javax.swing.JTextField();
        txtTPerimetro = new javax.swing.JTextField();
        btnTCalcularArea = new javax.swing.JButton();
        btnTCalcularPerimetro = new javax.swing.JButton();
        btnTCalcularHipotenusa = new javax.swing.JButton();
        btnTBorrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Radio");

        jLabel2.setText("Area");

        jLabel3.setText("Perimetro");

        btnArea.setText("Calcular Area");
        btnArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAreaActionPerformed(evt);
            }
        });

        btnPerimetro.setText("Calcular Perimetro");
        btnPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPerimetroActionPerformed(evt);
            }
        });

        btnCiBorrar.setText("Borrar");
        btnCiBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCiBorrarActionPerformed(evt);
            }
        });

        jLabel4.setText("Circulo");

        jLabel5.setText("Cuadrado");

        jLabel6.setText("Lado");

        jLabel7.setText("Area");

        jLabel8.setText("Perimetro");

        txtCuPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCuPerimetroActionPerformed(evt);
            }
        });

        btnCuCalcularArea.setText("Calcular Area");
        btnCuCalcularArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuCalcularAreaActionPerformed(evt);
            }
        });

        btnCuCalcularPerimetro.setText("Calcular Perimetro");
        btnCuCalcularPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuCalcularPerimetroActionPerformed(evt);
            }
        });

        btnCuBorrar.setText("Borrar");
        btnCuBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCuBorrarActionPerformed(evt);
            }
        });

        jLabel9.setText("Rectangulo");

        jLabel10.setText("Base");

        jLabel11.setText("Altura");

        jLabel12.setText("Area");

        jLabel13.setText("Perimetro");

        btnRCalcularArea.setText("Calcular Area");
        btnRCalcularArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRCalcularAreaActionPerformed(evt);
            }
        });

        btnRCalcularPerimetro.setText("Calcular Perimetro");
        btnRCalcularPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRCalcularPerimetroActionPerformed(evt);
            }
        });

        btnRBorrar.setText("Borrar");
        btnRBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRBorrarActionPerformed(evt);
            }
        });

        jLabel14.setText("Triangulo");

        jLabel15.setText("Base");

        jLabel16.setText("Altura");

        jLabel17.setText("Hipotenusa");

        jLabel18.setText("Area");

        jLabel19.setText("Perimetro");

        btnTCalcularArea.setText("Calcular Area");
        btnTCalcularArea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTCalcularAreaActionPerformed(evt);
            }
        });

        btnTCalcularPerimetro.setText("Calcular Perimetro");
        btnTCalcularPerimetro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTCalcularPerimetroActionPerformed(evt);
            }
        });

        btnTCalcularHipotenusa.setText("Calcular Hipotenusa");
        btnTCalcularHipotenusa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTCalcularHipotenusaActionPerformed(evt);
            }
        });

        btnTBorrar.setText("Borrar");
        btnTBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTBorrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(114, 114, 114)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(178, 178, 178))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(48, 48, 48))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(26, 26, 26)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCArea, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                            .addComponent(txtCPerimetro)
                            .addComponent(txtCRadio))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(234, 234, 234)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addGap(41, 41, 41))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addGap(18, 18, 18)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCuLado, javax.swing.GroupLayout.DEFAULT_SIZE, 106, Short.MAX_VALUE)
                            .addComponent(txtCuArea)
                            .addComponent(txtCuPerimetro)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnPerimetro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCiBorrar)
                        .addGap(88, 88, 88)
                        .addComponent(btnCuCalcularArea)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCuCalcularPerimetro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCuBorrar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel10))
                                .addGap(32, 32, 32)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtRAltura)
                                    .addComponent(txtRArea)
                                    .addComponent(txtRPerimetro)
                                    .addComponent(txtRBase, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnRCalcularArea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRCalcularPerimetro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnRBorrar)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(104, 104, 104)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel19)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel18)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTArea, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel17)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTHipotenusa, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtTAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel15)
                                        .addGap(43, 43, 43)
                                        .addComponent(txtTBase, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btnTBorrar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(btnTCalcularArea)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTCalcularPerimetro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTCalcularHipotenusa)))))
                .addContainerGap(9, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(110, 110, 110)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addGap(189, 189, 189))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtCRadio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtCuLado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtCuArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(txtCuPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnArea)
                    .addComponent(btnPerimetro)
                    .addComponent(btnCiBorrar)
                    .addComponent(btnCuCalcularArea)
                    .addComponent(btnCuCalcularPerimetro)
                    .addComponent(btnCuBorrar))
                .addGap(58, 58, 58)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel14))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtRBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(txtTBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel16)
                        .addComponent(txtTAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtRArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel17)
                        .addComponent(txtTHipotenusa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtRPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel18)
                    .addComponent(txtTArea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnRCalcularArea)
                            .addComponent(btnRCalcularPerimetro)
                            .addComponent(btnRBorrar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(txtTPerimetro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(btnTBorrar)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnTCalcularArea)
                            .addComponent(btnTCalcularPerimetro)
                            .addComponent(btnTCalcularHipotenusa))))
                .addContainerGap(55, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAreaActionPerformed

        double area;
        int Radio = Integer.parseInt(txtCRadio.getText());
        Circulo figura1 = new Circulo(Radio);
        area = figura1.calcularArea();
        txtCArea.setText(String.valueOf(area));
    }//GEN-LAST:event_btnAreaActionPerformed

    private void btnPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPerimetroActionPerformed
        double perimetro;
        int Radio = Integer.parseInt(txtCRadio.getText());
        Circulo figura1 = new Circulo(Radio);
        perimetro = figura1.calcularPerimetro();
        txtCPerimetro.setText(String.valueOf(perimetro));
    }//GEN-LAST:event_btnPerimetroActionPerformed

    private void btnCiBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCiBorrarActionPerformed
        txtCRadio.setText("");
        txtCArea.setText("");
        txtCPerimetro.setText("");
    }//GEN-LAST:event_btnCiBorrarActionPerformed

    private void btnCuCalcularAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuCalcularAreaActionPerformed
        double area;
        int Lado = Integer.parseInt(txtCuLado.getText());
        Cuadrado figura3 = new Cuadrado(Lado);
        area = figura3.calcularArea();
        txtCuArea.setText(String.valueOf(area));
    }//GEN-LAST:event_btnCuCalcularAreaActionPerformed

    private void btnCuCalcularPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuCalcularPerimetroActionPerformed
        double perimetro;
        int Lado = Integer.parseInt(txtCuLado.getText());
        Cuadrado figura3 = new Cuadrado(Lado);
        perimetro = figura3.calcularPerimetro();
        txtCuPerimetro.setText(String.valueOf(perimetro));
    }//GEN-LAST:event_btnCuCalcularPerimetroActionPerformed

    private void txtCuPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCuPerimetroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCuPerimetroActionPerformed

    private void btnCuBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCuBorrarActionPerformed
        txtCuLado.setText("");
        txtCuArea.setText("");
        txtCuPerimetro.setText("");
    }//GEN-LAST:event_btnCuBorrarActionPerformed

    private void btnRCalcularAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRCalcularAreaActionPerformed
        double area;
        int base = Integer.parseInt(txtRBase.getText());
        int altura = Integer.parseInt(txtRAltura.getText());
        Rectangulo figura2 = new Rectangulo(base,altura);
        area = figura2.calcularArea();
        txtRArea.setText(String.valueOf(area));
    }//GEN-LAST:event_btnRCalcularAreaActionPerformed

    private void btnRCalcularPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRCalcularPerimetroActionPerformed
        double perimetro;
        int base = Integer.parseInt(txtRBase.getText());
        int altura = Integer.parseInt(txtRAltura.getText());
        Rectangulo figura2 = new Rectangulo(base,altura);
        perimetro = figura2.calcularPerimetro();
        txtRPerimetro.setText(String.valueOf(perimetro));
    }//GEN-LAST:event_btnRCalcularPerimetroActionPerformed

    private void btnRBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRBorrarActionPerformed
        txtRBase.setText("");
        txtRAltura.setText("");
        txtRArea.setText("");
        txtRPerimetro.setText("");
    }//GEN-LAST:event_btnRBorrarActionPerformed

    private void btnTCalcularAreaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTCalcularAreaActionPerformed
        double area;
        int base = Integer.parseInt(txtTBase.getText());
        int altura = Integer.parseInt(txtTAltura.getText());
        TrianguloRectangulo figura4 = new TrianguloRectangulo(base,altura);
        area = figura4.calcularArea();
        txtTArea.setText(String.valueOf(area));
    }//GEN-LAST:event_btnTCalcularAreaActionPerformed

    private void btnTCalcularPerimetroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTCalcularPerimetroActionPerformed
        double perimetro;
        int base = Integer.parseInt(txtTBase.getText());
        int altura = Integer.parseInt(txtTAltura.getText());
        TrianguloRectangulo figura4 = new TrianguloRectangulo(base,altura);
        perimetro = figura4.calcularPerimetro();
        txtTPerimetro.setText(String.valueOf(perimetro));
    }//GEN-LAST:event_btnTCalcularPerimetroActionPerformed

    private void btnTCalcularHipotenusaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTCalcularHipotenusaActionPerformed
        double hipotenusa;
        int base = Integer.parseInt(txtTBase.getText());
        int altura = Integer.parseInt(txtTAltura.getText());
        TrianguloRectangulo figura4 = new TrianguloRectangulo(base,altura);
        hipotenusa = figura4.calcularHipotenusa();
        txtTHipotenusa.setText(String.valueOf(hipotenusa));
    }//GEN-LAST:event_btnTCalcularHipotenusaActionPerformed

    private void btnTBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTBorrarActionPerformed
        txtTBase.setText("");
        txtTAltura.setText("");
        txtTArea.setText("");
        txtTPerimetro.setText("");
        txtTHipotenusa.setText("");
    }//GEN-LAST:event_btnTBorrarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnArea;
    private javax.swing.JButton btnCiBorrar;
    private javax.swing.JButton btnCuBorrar;
    private javax.swing.JButton btnCuCalcularArea;
    private javax.swing.JButton btnCuCalcularPerimetro;
    private javax.swing.JButton btnPerimetro;
    private javax.swing.JButton btnRBorrar;
    private javax.swing.JButton btnRCalcularArea;
    private javax.swing.JButton btnRCalcularPerimetro;
    private javax.swing.JButton btnTBorrar;
    private javax.swing.JButton btnTCalcularArea;
    private javax.swing.JButton btnTCalcularHipotenusa;
    private javax.swing.JButton btnTCalcularPerimetro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtCArea;
    private javax.swing.JTextField txtCPerimetro;
    private javax.swing.JTextField txtCRadio;
    private javax.swing.JTextField txtCuArea;
    private javax.swing.JTextField txtCuLado;
    private javax.swing.JTextField txtCuPerimetro;
    private javax.swing.JTextField txtRAltura;
    private javax.swing.JTextField txtRArea;
    private javax.swing.JTextField txtRBase;
    private javax.swing.JTextField txtRPerimetro;
    private javax.swing.JTextField txtTAltura;
    private javax.swing.JTextField txtTArea;
    private javax.swing.JTextField txtTBase;
    private javax.swing.JTextField txtTHipotenusa;
    private javax.swing.JTextField txtTPerimetro;
    // End of variables declaration//GEN-END:variables
}
